### ISSUE TITLE
Docs improvement

### ISSUE THREAD

**Issue by nktssh** [pafnuty/sublime-yandex-translate#11]
It will be better to mention that I need to put my settings for this package inside `yaTranslate.sublime-settings` file (Package Settings level), not into `User/Preferences.sublime-settings` - spent about 15 minutes to figure out why I've always get  "API Key not defined!" 😑

**Comment by ildarkhasanshin** [comment]
а зачем api-ключ должен быть в User/Preferences.sublime-settings?

**Comment by nktssh** [comment]
@ildarkhasanshin 
Дак незачем)
В доках указано:
`Set API-key in user settings`
а по факту класть ключ нужно в `yaTranslate.sublime-settings`

В русских доках указано, что именно в файл настроек плагина
`Вставьте полученый API key в файл настроек плагина`

Предлагаю и в английском сделать, чтобы понятно было сразу, куда именно класть ..

**Comment by ildarkhasanshin** [comment]
https://github.com/pafnuty/sublime-yandex-translate/pull/12

**Comment by pafnuty** [comment]
@nktssh, @ildarkhasanshin спасибо за замечания и исправления! 
merged!
