### ISSUE TITLE
Slow translating

### ISSUE THREAD

**Issue by djdeo** [pafnuty/sublime-yandex-translate#14]
Don't know if this is an issue, but no matter it's a single line or multiple line translation, it's slow even when the network is fine

**Comment by pafnuty** [comment]
Hi @djdeo!
I suppose translation speed depends on yandex side

**Comment by djdeo** [comment]
make sense, thanks

2018-03-25 0:26 GMT+08:00 Pavel Belousov <notifications@github.com>:
