### ISSUE TITLE
дополнительный хоткей

### ISSUE THREAD

**Issue by ildarkhasanshin** [pafnuty/sublime-yandex-translate#5]
неудобно переключаться между en->ru и ru->en, к примеру
возможно добавить дополнительную опцию (output_language2) и хоткей
чтоб одним хоткеем можно было output_language->output_language2
вторым - output_language2->output_language

**Comment by ildarkhasanshin** [comment]
а еще лучше
единый хоткей между output_language и output_language2
но здесь наверное мороки много с автоопределением языка

**Comment by pafnuty** [comment]
Я обычно нажимаю `Ctrl+Alt+T` и если выделенный текст на кириллице, то показывается выпадающее меню.

Думаю можно будет сделать так, что если текст совпадает с тем языком, на который требуется перевести, он будет переведён на язык, указанный в output_language2. Можно будет одну и ту же фразу туда-сюда переводить одним сочетанием клавиш.

**Comment by ildarkhasanshin** [comment]
> Я обычно нажимаю Ctrl+Alt+T и если выделенный текст на кириллице, то показывается выпадающее меню.
в том то и дело, шо так муторно

**Comment by pafnuty** [comment]
Готово https://github.com/pafnuty/sublime-yandex-translate/commit/3b638b15df109eba014f658962433bdbfc15e757
